#
# NODE_ENV=development
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Console'
  org': 'Laconic.org'
  theme: 'dark'
  website: 'https://laconic.com'
  publicUrl: '/console'

api:
  path: '/api'
  port: 9004
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'laconic:console:*'

services:
  app:
    prefix: '/app'
    server: 'https://apollo1.kube.moon.laconic.network'

  wns:
    server: 'https://apollo1.kube.moon.laconic.network/laconic/wns/api'
    webui: 'https://apollo1.kube.moon.laconic.network/laconic/wns/console'

  signal:
    server: 'wss://apollo1.kube.moon.laconic.network/laconic/signal'
    api: 'https://apollo1.kube.moon.laconic.network/laconic/signal/api'

  ipfs:
    server: 'https://apollo1.kube.moon.laconic.network/laconic/ipfs/api'
    gateway: 'https://apollo1.kube.moon.laconic.network/laconic/ipfs/gateway'

  wellknown:
    endpoint: 'https://apollo1.kube.moon.laconic.network/.well-known/laconic'
