#
# NODE_ENV=production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Console'
  org: 'Laconic.org'
  theme: 'dark'
  website: 'https://laconinc.com'
  publicUrl: '/console'

api:
  path: '/api'
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'laconic:console:*'

routes:
  app:
    server: '/app'

  wns:
    server: '/laconic/wns/api'
    webui: '/laconic/wns/console'

  signal:
    api: '/laconic/signal/api'

  ipfs:
    server: '/laconic/ipfs/api'
    gateway: '/laconic/ipfs/gateway'

  wellknown:
    endpoint: '/.well-known/laconic'
