#
# NODE_ENV === production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Console'
  org': 'DxOS'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'

api:
  path: '/api'
  port: 4000
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:console:*'

services:
  app:
    prefix: '/app'
    server: 'http://127.0.0.1:5999'

  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/webui'

  signal:
    server: 'ws://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000'

  ipfs:
    server: 'https://127.0.0.1:5001'
    gateway: 'http://127.0.0.1:8888'

  wellknown:
    endpoint: 'http://127.0.0.1:9000/.well-known/dxos'

routes:
  app:
    server: '/app'

  wns:
    server: '/dxos/wns/api'
    webui: '/dxos/wns/console'

  signal:
    api: '/dxos/signal'

  ipfs:
    server: '/dxos/ipfs/api'
    gateway: '/dxos/ipfs/gateway'

  wellknown:
    endpoint: '/.well-known/dxos'
